src/Vortice.Direct2D1/ID2D1RenderTarget.cs
Without cast, CreateLinearGradientBrush call itself and throw StackOverflowException.
=> Fix StackOverFlowException

src/Vortice.DXGI/IDXGIFactory5.cs, src/Vortice.DXGI/IDXGISwapChain4.cs, src/Vortice.Direct2D1/DirectWrite/GlyphRun.cs, src/Vortice.Direct2D1/Effects/ConvolveMatrix.cs, src/Vortice.Direct2D1/Effects/DiscreteTransfer.cs, src/Vortice.Direct2D1/Effects/Histogram.cs, src/Vortice.Direct2D1/Effects/TableTransfer.cs, src/Vortice.Direct2D1/ID2D1EffectContext.cs, src/Vortice.Direct2D1/ID2D1TransformShadow.cs, src/Vortice.Direct2D1/WIC/IWICBitmapFrameEncode.cs, src/Vortice.Direct2D1/WIC/IWICBitmapSource.cs, src/Vortice.Direct3D11/D3D11.cs, src/Vortice.Direct3D11/ID3D11Device.cs, src/Vortice.Direct3D11/ID3D11Device3.cs, src/Vortice.Direct3D11/ID3D11DeviceContext.cs, src/Vortice.Direct3D11/ID3D11DeviceContext1.cs, src/Vortice.Direct3D12/CommandSignatureDescription.cs, src/Vortice.Direct3D12/GraphicsPipelineStateDescription.cs, src/Vortice.Direct3D12/ID3D12Device.cs, src/Vortice.Direct3D12/ID3D12GraphicsCommandList.cs, src/Vortice.Direct3D12/ID3D12Resource.cs, src/Vortice.Direct3D9/IDirect3DDevice9.cs, src/Vortice.DirectX/Interop.cs, src/Vortice.Runtime.COM/Win32/ComStreamProxy.cs, src/Vortice.XAudio2/AudioBuffer.cs, src/Vortice.XAudio2/Emitter.cs, src/Vortice.XAudio2/IXAudio2Voice.cs, src/Vortice.XAudio2/Listener.cs
- As the name implies, ``Unsafe.AsPointer`` is to be used with great caution. It is by no means a replacement for the ``fixed`` statement. It does nothing to prevent managed variables (e.g. arrays) from being relocated.
There are only two uses of ``Unsafe.AsPointer`` left in the codebase ([Listener.cs](https://github.com/SomeAnonDev/Vortice.Windows/blob/ba6ef8ada47834f79c91da270564a1118b650ca6/src/Vortice.XAudio2/Listener.cs#L46) and [Emitter.cs](https://github.com/SomeAnonDev/Vortice.Windows/blob/ba6ef8ada47834f79c91da270564a1118b650ca6/src/Vortice.XAudio2/Emitter.cs#L112)). ``__Native`` never lives on the heap, and as long as the native code doesn't store the pointer to ``Cone``, it should be fine.
- e6205b3 fixes a problem where a pointer to a local variable was stored in a struct that …
=> Fix a number of memory safety issues

src/Vortice.Direct2D1/Mappings.xml
It painful to write code like this
```
int actualLineCount=0;
try
{
textlayout.GetLineMetrics(null, 0, out actualLineCount);
}
catch
{
var lineMetrics = new LineMetrics1[actualLineCount];
if (actualLineCount > 0)
{
GetLineMetrics(lineMetrics, lineMetrics.Length, out _);
}
return lineMetrics;
}
return new LineMetrics1[0];
```
so it's better to let these methods return hresult.
If you want to let these methods work like [IDWriteTextLayout.GetLineMetrics](https://github.com/amerkoleci/Vortice.Windows/blob/master/src/Vortice.Direct2D1/DirectWrite/IDWriteTextLayout.cs) that good but I believed my commit is ok. And either is better than it is now.
=> let HitTestTextRange and GetLineMetrics return hresult

src/Vortice.Direct2D1/DirectWrite/IDWriteFontCollectionLoader.cs
repro : https://github.com/yinyue200/SpanDxTest
```
Generating code...
1>    Interop code generated.
1>  Compiling interop code
1>  Generating System.Reflection.DispatchProxy proxy code.
1>  Cleaning up unreferenced code
1>  Generating native code
1>C:\Users\username\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\Microsoft.NetNative.targets(801,5): error : Error: NUTC300D:Internal Compiler Error: Type 'System.Span`1<System.Byte>' is not valid for use outside of the managed environment, but is passed to native code while compiling method 'static System.Int32 __Interop.Intrinsics.StdCall__97(System.IntPtr, System.Void*, System.Void*, System.Span`1<System.Byte>, System.Void*)'.
1>C:\Users\username\.nuget\packages\microsoft.net.native.compiler\2.2.8-rel-28605-00\tools\M …
```
=>  workaround for dotnet/runtime#35171

src/Vortice.Runtime.COM/VorticePlatformDetection.cs, src/Vortice.XInput/XInput.cs
RtlGetVersion  is not allowed in uwp apps. This pr replaces RtlGetVersion with GetVersionExW which is allowed by the WACK tool.
Here is an example of WACK failing report:
Supported API test
FAILED
Supported APIs
Error Found: The supported APIs test detected the following errors:
API RtlGetVersion in ntdll.dll is not supported for this application type. example.dll calls this API.
Impact if not fixed: Using an API that is not part of the Windows SDK for Microsoft Store apps violates the Microsoft Store certification requirements.
How to fix: Review the error messages to identify the API that is not part of the Windows SDK for Microsoft Store apps. Please note, apps that are built in a debug configuration or without .NET Native enabled (where applicable) can fail this test as these …
=> fix Windows App Certification Kit (WACK) failure

src/Vortice.Direct2D1/DirectWrite/IDWriteFontCollectionLoader.cs, src/Vortice.Direct2D1/DirectWrite/IDWriteFontFileEnumerator.cs, src/Vortice.Runtime.COM/ComObjectShadow.cs, src/Vortice.Runtime.COM/InspectableShadow.cs
This fixes #100 for me,  although I am not quite sure _why_, since it should have kept them alive regardless. But this does ensure the vtables never go away so this cannot happen again.
Additionally I noticed the following: The vtables are allocated in unmanaged memory, and _never_ released, meaning that this also fixes a memory leak since the vtable is currently being allocated per-shadow, and is **never** freed.
What is somewhat worrisome: The vtable's also seem to be per-shadow in the generated shadow interfaces.... I don't know what to do about these.
=> Make more vtables static to avoid reallocating them for every shadow object

src/Vortice.DirectX/DataStream.cs
Simple helper function that allows for basepointer to be referenced without having to play with the Position.
=> Basepointer added to allow for PositionPointer to remain undisturbed

src/Vortice.XAudio2/Vortice.XAudio2.csproj, src/Vortice.XAudio2/Vortice.XAudio2.targets
Add targets file to XAudio NuGet package to ensure assemblies are copied to output on build.
In reference to #122 **Vortice XAudio2 causing exception on latest Windows**
=> Add targets file to XAudio NuGet package

src/Vortice.XAudio2/Vortice.XAudio2.csproj
Target is not needed in buildMultiTargeting. Tested on local machine and still works properly.
=> Remove XAudio2 targets from buildMultiTargeting since it is not needed.

src/Vortice.Dxc/DxcCompiler.cs, src/Vortice.Dxc/DxcCompilerOptions.cs
I'm using DXC to compile HLSL to SPIR-V, then using SPIRV-Cross to generate GLSL for source code for OpenGL and Vulkan.
I ran into some issues due to alignment differences so adding options to set the layout in the options object.
=> Add layout properties to DXC options.

src/Vortice.Dxc/DxcValidatorFlags.cs, src/Vortice.Dxc/Dxil.cs, src/Vortice.Dxc/IDxcValidator.cs, src/Vortice.Dxc/Mappings.xml
Compiling shaders with DXC was failing to sign the code even though dxil.dll was next to dxcompiler.dll.
In order to get around the issue I tried loading dxil.dll manually to help find the DLL but the compiler was still saying it was missing. I think this is due to the fact that I was running it in an MSBuild task and it was searching next to the MSBuild exe since it appears dxcompiler.dll needs to find dxil.dll.
I tried validating manually but it still didn't work. I discovered that `IDxcValidator` must be created by PInvoking to dxil.dll directly. I just copied the generated code from DXC and changed the assembly name. I also updated the flags property to the proper enum.
I got the hint from here: https://www.wihlidal.com/blog/pipeline/2018-09-16-dxil-signing-post-compile/
and here: …
=> Add DXIL validator support.

src/Vortice.XAudio2/AudioBuffer.cs
Pull request is more informational but the change may need some verification.
Code implementation is executing high pitch sound replay/distortion.
```
SoundStream soundSample_ = new SoundStream(fileStream_);
_targetBuffer = new AudioBuffer(soundSample_);
int encodng_ = (int)soundSample_.Format.Encoding;
_waveFormat = soundSample_.Format;
uint[] _encoding = soundSample_.DecodedPacketsInfo;
```
presents sound distortion and high frequency playback among things.  I've changed the audiobuffer function code to copy the buffer in and set OwnBuffer.  I believe this will fix some strange underlying issue.  The sample below works as I have used the alternative constructor in the code below, In this sample I copy the stream to a byte buffer to invoke a constructor that does copy the data in and set …
=> Memory allocation issues - playback distortion

src/tests/Vortice.D3DCompiler.Test/CompileTests.cs, src/tests/Vortice.Dxc.Test/CompileTests.cs
I ran into a compile error with D3DCompiler when compiling with ShaderMacro a couple weeks ago. I narrowed the issue down to the fact that the array must be NULL terminated.
>Pointer to an array of macro definitions (see D3D10_SHADER_MACRO). The last structure in the array serves as a terminator and must have all members set to 0.
https://docs.microsoft.com/en-us/windows/win32/api/d3d10shader/nf-d3d10shader-d3d10compileshader
I checked today and it is no longer causing an error. I suspect that this may just be a coincidence that the memory after the array is clear. Unless you have made a change to add the NULL termination but it doesn't look like it.
I'm not sure if this would be considered a bug since it is documented, but if the error arises again the proper fix is this which I use in …
=> Shader compiler constants test.

src/Vortice.Dxc/Dxc.cs, src/Vortice.Dxc/Dxil.cs
AFAIK since these methods call CheckError() it is guaranteed that the result must be non-null.
Also, there are a lot of overloads in Vortice.Dxc that return a nullable object (e.g. DxcCompiler.Compile(string, string[], IDxcIncludeHandler?)) without calling CheckError(). These are not too useful IMO because you can only tell if there was an error or not (result == null) but you can't tell what the error was. What do you think about changing these methods to return a non-nullable object (i.e. adding CheckError() to these methods)? This would be a breaking change but it's likely to make people's code cleaner since the currently needed null checks would no longer be necessary. I can do a PR if you're okay with the change.
=> Dxc methods should return a non-nullable object since CheckError() is called

src/Vortice.Dxc/DxcCompiler.cs, src/Vortice.Dxc/IDxcCompiler.cs, src/Vortice.Dxc/IDxcCompiler2.cs, src/Vortice.Dxc/IDxcCompiler3.cs, src/Vortice.Dxc/IDxcExtraOutputs.cs, src/Vortice.Dxc/IDxcLinker.cs, src/Vortice.Dxc/IDxcPdbUtils.cs, src/Vortice.Dxc/IDxcResult.cs, src/Vortice.Dxc/IDxcUtils.cs, src/tests/Vortice.Dxc.Test/CompileTests.cs
If these methods fail they now throw an exception instead of returning null. If throwing an exception is undesired, users can call the Result-returning overloads instead.
I notice IDxcIncludeHandler.LoadSource() has incorrect nullability (includeSource should be nullable), but I'm unsure how to fix it as it is in the generated code (is there a nullability option in Mappings.xml?)
=> Breaking change: return non-nullable interfaces from Dxc methods.

src/Vortice.Direct3D12/D3D12.cs, src/Vortice.Direct3D12/ID3D12VersionedRootSignatureDeserializer.cs, src/Vortice.Direct3D12/Mappings.xml
Plus I added a usable version of ID3D12VersionedRootSignatureDeserializer.GetRootSignatureDescAtVersion().
I've tested these two methods and they both work fine, but unfortunately ID3D12VersionedRootSignatureDeserializer.GetUnconvertedRootSignatureDescription() doesn't seem to work.
I think this might be because the delegate indicates a Vortice.Direct3D12.VersionedRootSignatureDescription.__Native is returned but the method itself returns a pointer...? I don't know how to change that in the mappings, so I can't check to find out. Any ideas or tips on how to make this work?
=> Add missing public D3D12CreateVersionedRootSignatureDeserializer() method

src/Vortice.Direct2D1/DirectWrite/IDWriteFontFace.cs
IDWriteFontFace.cs's implementation was erroneously calling itself rather than the Interfaces.cs version that has isSideways as a RawBool. By explicitly type-casting, we can avoid this issue.
````
Stack overflow.
Repeat 19375 times:
--------------------------------
at Vortice.DirectWrite.IDWriteFontFace.GetDesignGlyphMetrics(UInt16[], Vortice.DirectWrite.GlyphMetrics[], Boolean)
--------------------------------
at Vortice.DirectWrite.IDWriteFontFace.GetDesignGlyphMetrics(UInt16[], Boolean)
at [my code]
at [my code]
at [my code]
````
No infinite recursion.
=> FIX: IDWriteFontFace.GetDesignGlyphMetrics Infinite Recursion

src/Vortice.DirectStorage/Mappings.xml, src/Vortice.DirectStorage/Request.cs, src/Vortice.DirectStorage/RequestOptions.cs, src/samples/HelloDirectStorage/HelloDirectStorage.csproj, src/samples/HelloDirectStorage/Test.txt
* Request.Source and Request.Destination are unions, and the marshalling was reading/writing every member of the union. I've fixed it so that only a single member of these structures is marshalled.
* According to my testing in C++, RequestOptions is 16 bytes, with the compression format taking the first 8 bytes and the source and destination types taking the second 8 bytes. Looking at the struct definition I would not have guessed this to be the case.
* I added the test.txt file that the DirectStorage sample needs.
* The CompressionFormat enum had some broken names, so I fixed it.
=> Fix marshalling for DirectStorage Request & RequestOptions structures

src/Vortice.Direct2D1/DirectWrite/ColorGlyphRun.cs, src/Vortice.Direct2D1/DirectWrite/ColorGlyphRun1.cs
ColorGlyphRun stores a pointer to a GlyphRunDescription struct; it doesn't actually embed the struct in itself.
This fixes the MarshalFrom implementations of ColorGlyphRun and ColorGlyphRun1 to correctly marshal the data. 
Without this change, unmarshalling ColorGlyphRun(1) is reading invalid data and has a good chance of segfaulting.
=> FIX: ColorGlyphRun marshalling of GlyphRunDescription

src/Vortice.Direct2D1/Effects/ConvolveMatrix.cs, src/Vortice.Direct2D1/Effects/Histogram.cs, src/Vortice.Direct2D1/Effects/Morphology.cs, src/Vortice.Direct2D1/Effects/Posterize.cs, src/Vortice.Direct2D1/Effects/Turbulence.cs
Fixed several properties that were failing to set and get.
These properties must be set/get with uint.
- ConvolveMatrix.KernelSizeX / KernelSizeY
- Histogram.NumBins
- Morphology.Width / Height
- Posterize.RedValueCount / GreenValueCount / BlueValueCount
- Turbulence.NumOctaves
[The documents](https://docs.microsoft.com/en-us/windows/win32/api/d2d1effects/ne-d2d1effects-d2d1_turbulence_prop) say that `Turbulence.Seed` must be uint, but in reality, failed to set/get with uint.
So, `Turbulence.Seed` is keep as int.
=> Fix effect property setter/getter type

src/Vortice.Direct2D1/Effects/ColorManagement.cs, src/Vortice.Direct2D1/ID2D1Properties.cs
I don't know why, but when I set `ColorContext` as `PropertyType.IUnknown`, I get `0x80000003` error code on the application exits.
When using `PropertyType.ColorContext`, the application exits normally.
=> Fix ColorContext as PropertyType.ColorContext instead of PropertyType.IUnknown

src/Vortice.MediaFoundation/IMFAttributes.cs, src/Vortice.MediaFoundation/Mappings.xml
I fixed some issues related to MediaFoundation.
Fixed `EntryPointNotFoundException` due to incorrectly `dll` attribute
Hide reserved argument that requires passing `IntPtr.Zero`.
`internal void Set(...)` was not being called due to duplicate names, resulting in infinite recursion.
Renamed `internal void Set(...)` to `internal void Set_(...)`.
Due to an overload problem, `Set<long>(value)` was being passed to `internal Set_(double value)`.
long value is now cast to ulong.
Fixed potential OverflowException.
Such as: `Convert.ToInt32(uint.MaxValue)`
=> Fix some MediaFoundation issue

src/Vortice.MediaFoundation/Mappings.xml
I fixed some IMFTransform.ProcessOutput() issues.
---
```xml
<map param="IMFTransform::ProcessOutput::dwFlags" type="_MFT_PROCESS_OUTPUT_FLAGS"/>
<map param="IMFTransform::ProcessOutput::pdwStatus" type="_MFT_PROCESS_OUTPUT_STATUS" attribute="out"/>
```
Type specified to `dwFlags` and `pdwStatus`.
Added `out` attribute to `pdwStatus` to make the return value available.
---
```xml
<map param="IMFTransform::ProcessOutput::pOutputSamples" attribute="inout"/>
```
Added `inout` attribute to `pOutputSamples` to get IMFSample allocated in IMFTransform.
Example
```C#
var buffer = new TOutputDataBuffer();
var info = mft.GetOutputStreamInfo(0);
var flags = (OutputStreamInfoFlags)info.Flags;
if (flags.HasFlag(OutputStreamInfoFlags.OutputStreamProvidesSamples))
{
var res = …
```
=> Fix IMFTransform.ProcessOutput()

src/Vortice.Direct3D12/ID3D12GraphicsCommandList2.cs, src/Vortice.Direct3D12/ResourceBarrier.cs
For WriteBufferImmediate(), the modes parameter is nullable, see [here](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/nf-d3d12-id3d12graphicscommandlist2-writebufferimmediate). I removed an overload which doesn't seem to be needed but which is a small breaking change; feel free to revert this if you don't like it.
The pResource parameter in the UAV barrier structure is optional, see [here](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_resource_uav_barrier).
Both resource parameters in the aliasing barrier structure are optional, see [here](https://docs.microsoft.com/en-us/windows/win32/api/d3d12/ns-d3d12-d3d12_resource_aliasing_barrier).
=> Nullability fixes for WriteBufferImmediate() and barriers

src/Vortice.Direct3D12/StaticSamplerDescription.cs
Minor fix to the sampler to static sampler conversion code, when the border color is set to opaque black or opaque white.
=> Fix for static sampler border color not being set correctly

src/Vortice.Direct3D12/ResourceDescription.cs, src/Vortice.Direct3D12/ResourceDescription1.cs
.Net prefers signed numbers even when the numbers should only be unsigned. As such, we should allow overrides creating resources with them.
=> D3D12: Better ResourceDescription support for signed numbers

src/Vortice.XAudio2/Mappings.xml
XAUDIO2_MAX_BUFFER_BYTES is defined to be 0x80000000 in C++, which is too large for a signed int. In Vortice it wraps around into the negatives, meaning code like `if (myBufferSize >= XAudio2.MaxBufferBytes)` will always be true.
=> MaxBufferBytes is too large for a signed int

src/Vortice.Direct3D12/ID3D12Device4.cs, src/Vortice.Direct3D12/ID3D12Device7.cs
The Create() methods in ID3D12Device4 and ID3D12Device7 do accept the GUIDs of base types, and it's often convenient to use the earlier versions of these interfaces.
=> Fix methods in ID3D12Device4 and ID3D12Device7 so they accept base types.

src/Vortice.Direct3D12/ID3D12Object.cs
The main fix is to make the string non-nullable, but I put a null check in as well just to be safe. Do we still need to check for null if the parameter is non-nullable? I guess yes because not everyone will have nullability enabled.
=> Fix access violation when setting Name = null

src/Vortice.UIAnimation/IUIAnimationManager.cs, src/Vortice.UIAnimation/IUIAnimationManager2.cs, src/Vortice.UIAnimation/IUIAnimationTimer.cs, src/Vortice.UIAnimation/IUIAnimationTransition2.cs, src/Vortice.UIAnimation/IUIAnimationTransitionFactory.cs, src/Vortice.UIAnimation/IUIAnimationTransitionFactory2.cs, src/Vortice.UIAnimation/IUIAnimationTransitionLibrary.cs, src/Vortice.UIAnimation/IUIAnimationTransitionLibrary2.cs, src/Vortice.UIAnimation/IUIAnimationVariableChangeHandler2.cs, src/Vortice.UIAnimation/IUIAnimationVariableChangeHandler2Vtbl.cs, src/Vortice.UIAnimation/IUIAnimationVariableIntegerChangeHandler2.cs, src/Vortice.UIAnimation/IUIAnimationVariableIntegerChangeHandler2Vtbl.cs
This is caused by the `©` sign in first line.
I checked all other code, it's all using `utf-8`, but for reason unknown only this UIAnimation project is using `Western (Mac Roman)`, causing will popup a error(only this UIAnimation project, all other project is good):
=> UIAnimation not using utf-8 causing error when open in Windows VS.

src/Vortice.Direct3D12/ID3D12GraphicsCommandList.cs
I added this overload to avoid array allocations:
```
public void OMSetRenderTargets(ReadOnlySpan<CpuDescriptorHandle> renderTargetDescriptors, CpuDescriptorHandle? depthStencilDescriptor = null)
```
I removed this overload because submitting the start of an array is not common and can easily be done using span slices:
```
public void OMSetRenderTargets(int renderTargetDescriptorsCount, CpuDescriptorHandle[] renderTargetDescriptors, CpuDescriptorHandle? depthStencilDescriptor = null)
```
Plus I removed these overloads because the parameters don't make sense when `RTsSingleHandleToDescriptorRange` is true:
```
public void OMSetRenderTargets(CpuDescriptorHandle renderTargetDescriptor, bool RTsSingleHandleToDescriptorRange, CpuDescriptorHandle? depthStencilDescriptor = null)
public void …
```
=> D3D12 OMSetRenderTargets overloads

src/Vortice.Direct2D1/ID2D1Factory1.cs
The correct name is GetRegisteredEffects, but it is now GetRegistere**ot**dEffects.
https://github.com/amerkoleci/Vortice.Windows/blob/63e46dc29156c56fbcb19097fc00db5127f20a67/src/Vortice.Direct2D1/ID2D1Factory1.cs#L37
=> Fix typo of GetRegisteredEffects

src/Vortice.MediaFoundation/IMFAttributes.cs
System.OverflowException may occur when converting from uint to int, ulong to long, or UIntPtr to IntPtr.
Example:
```C#
Convert.ChangeType(ulong.MaxValue, typeof(long)); //System.OverflowException
```
Fixed:
```C#
Convert.ChangeType(unchecked((long)ulong.MaxValue), typeof(long)); //success
```
=> Fix System.OverflowException in IMFAttributes.Get<T>(Guid guidKey);

src/Vortice.Direct2D1/ID2D1Geometry.cs
This PR resolves an infinite recursion issue #480 in the following method: ```ID2D1Geometry.StrokeContainsPoint```.
=> Fix infinite recursion bug in ID2D1Geometry.StrokeContainsPoint

src/Vortice.Direct3D9/Mappings.xml, src/Vortice.MediaFoundation/MediaFactory.cs, src/Vortice.WinUI/Vortice.WinUI.csproj
More details: As the documentation of the IDirect3DDeviceManager9 class is already in the Vortice.Direct3D9 project, I've added the dxva2api header file here. Taking example of "d3d9on12" file header has already been added in this project but in a dedicated namespace, I reproduce the same architecture by putting the class IDirect3DDeviceManager9 in the new namespace  "Vortice.DirectXVA2api".
Following the SharpGen builds errors, I've "removed"  all the functions, structs and interfaces not needed for now.
=> Adding of the bindings for IDirect3DDeviceManager9 in namespace  "Vortice.DirectXVA2api".

src/Vortice.Direct3D12/ID3D12DescriptorHeap.cs
On Linux, vkd3d-native expects a pointer to a `D3D12_CPU_DESCRIPTOR_HANDLE` or `D3D12_GPU_DESCRIPTOR_HANDLE` to be passed as the second argument when calling `ID3D12DescriptorHeap::GetCPUDescriptorHandleForHeapStart` or `ID3D12DescriptorHeap::GetGPUDescriptorHandleForHeapStart`
=> Support vkd3d-native implementation of `ID3D12DescriptorHeap::GetCPUDescriptorHandleForHeapStart` on Linux
